server:
  port: 8001
 
spring:  application:    name: microservice-dept-provider
  datasource:    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud01?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    dbcp2:
      min-idle: 5                                     #数据库连接池最小维持连接数
      initial-size: 5                                 #初始化连接数
      max-total: 5                                    #最大连接数
      max-wait-millis: 200

mybatis:
  configuration: #mybatis配置
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
    use-generated-keys: true
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.naruto.springcloud.bean
  
eureka:  client:    service-url:      defaultZone: http://eureka7001.com:7001/eureka
  instance:    instance-id: microservice-dept-provider:8001
    prefer-ip-address: true