server:
  port: 9527

spring:
  application:
    name: microservice-zuul-gateway
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: microservice-zuul-gateway
    prefer-ip-address: true
zuul:
  ignored-services: "*" #microservice-dept-provider       #忽略源真实微服务名称； 忽略所有的微服务名称用"*"
  routes:
    mydept.serviceId: microservice-dept-provider #隐藏服务名称，用以下值来映射
    mydept.path: /dept/**   # http://localhost:9527/microservice-dept-provider/get/1 => http://localhost:9527/dept/get/1

