server:
  port: 3344

spring:
  application:
    name: microservice-config #服务名称serviceId
  cloud:
    config:
      server:
        git:
          uri: https://github.com/1456017852/spring-coud-config.git #github上面config仓库url

